packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': false
  '@tarojs/binding': false
  '@tarojs/cli': false
  bufferutil: false
  core-js: false
  core-js-pure: false
  esbuild: false
  less: false
  minidev: false
  prisma: true
  protobufjs: false
  swiper: false
